"""empty message

Revision ID: 137ae25db337
Revises: None
Create Date: 2020-06-30 11:30:56.108533

"""

# revision identifiers, used by Alembic.
revision = '137ae25db337'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
